### ISSUE TITLE
🐞: notificare_push ^4.0.0-beta.2 depends on notificare 3.0.0

### ISSUE THREAD

**Issue by andreasmpet** [Notificare/notificare-sdk-flutter#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Trying to use the 4.0.0 beta of notificare_plus requires me to downgrade to 3.0.0 of the notificare core library

### Steps to reproduce

Use the same version number for both packages.

  notificare: ^4.0.0-beta.2
  notificare_push: ^4.0.0-beta.2

### Expected behaviour

Expected notificare_push 4.0.0-beta.2 to depend on notificare 4.0.0-beta.2

### Library version

4.0.0-beta.2

### Operating system

iOS 18

### Flutter version

3.24.3

**Comment by hpinhal** [comment]
Hi @andreasmpet ,

Thanks for the heads up.
This issue is resolved in version 4.0.0, which will come out later today.

Stay tuned to the release on GitHub.
