### ISSUE TITLE
Listening to events onDeviceRegistered

### ISSUE THREAD

**Issue by carlomacias** [Notificare/notificare-sdk-flutter#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In 4.4.0, this listener does not invoke 

Notificare.onDeviceRegistered.listen((event) {
 print("Device registered");
});

Any Idea why?

### Steps to reproduce

I follow the instructions, 

[Notificare.onDeviceRegistered.listen((event)](https://docs.notifica.re/sdk/v4/flutter/implementation/#listening-to-events)

### Expected behaviour

Should invoke when registered. 

### Library version

4.0.0

### Operating system

Android 14

### Flutter version

3.24.3

**Comment by hpinhal** [comment]
Hello Carlo,

There is no need to reach out to us on several channels.
As my colleague explained via the support channel, this is part of the changes documented in the [migration guide](https://github.com/Notificare/notificare-sdk-flutter/blob/main/MIGRATION.md#device-registration-behavior).
The device identifier became long-lived. Therefore, there are no more registrations when changing between transports.

Quoting from the migration guide:
> In previous versions, the `onDeviceRegistered` event triggered when enabling or disabling remote notifications. With the new immutability of device identifiers, this event will now only trigger once — when the device is initially created.
>
> If you need to track changes when a device switches between a temporary and a push-enabled state (or vice versa), you can listen to the `onSubscriptionChanged` property, as demonstrated in the example above.
